### ISSUE TITLE
Loading `serverless-offline#environment-variables`

### ISSUE THREAD

**Issue by azizur** [apancutt/serverless-offline-dotenv#2]
I am trying to use your plugin with serverless-offline. However, it does not seem to load environment-variables as described at https://github.com/dherault/serverless-offline#environment-variables.

I am not fully sure what causes it to not load environment variables with `SLS_` prefix.

**Comment by apancutt** [comment]
Sorry I somehow missed the notification for this issue. Has the issue been resolved?

**Comment by azizur** [comment]
It's not resolved yet. Here are my changes https://github.com/apancutt/serverless-offline-dotenv/compare/master...azizur:master

Do let me know if you want me to raise a PR.

**Comment by apancutt** [comment]
Thanks for the issue report. Fixed in 0.1.0.
